name: Bug Report 🚨
description: Report a bug to help improve this project.
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: Thanks for being interested in contributing to this project! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Clear steps that describe how to reproduce the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details
      description: Provide information that may be helpful.
  - type: input
    id: version
    attributes:
      label: Version
      description: Specify the exact version.
      placeholder: '0.0.1'
  - type: markdown
    attributes:
      value: |
        Before posting, please go through the steps to make sure the information provided is clear and detailed.
        Your feedback is much appreciated. Thanks in advance!
