blank_issues_enabled: false
contact_links:
  - name: Questions & Help 🙋
    url: https://github.com/ivodolenc/nuxt-gsap-module/discussions
    about: Please use Discussions for all additional questions or technical advices.
