name: Feature Request 🚀
description: Suggest a new idea or a quick enhancement.
labels: 'feat'
body:
  - type: markdown
    attributes:
      value: Thanks for being interested in contributing to this project! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Request Description
      description: Describe what you'd like to see as a new enhancement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe the alternatives you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details
      description: Provide information that may be helpful.
  - type: markdown
    attributes:
      value: |
        Before posting, go through the steps to make sure the information provided is clear and detailed.
        Your feedback is much appreciated. Thanks in advance!
